FROM nginx:alpine

RUN rm -rf /usr/share/nginx/html/*

# Copy frontend build into nginx container
COPY frontend/dist/ /usr/share/nginx/html/

# Copy nginx config
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]